### ISSUE TITLE
pyenv_global seems to have no effect

### ISSUE THREAD

**Issue by daniel-vu** [avanov/ansible-galaxy-pyenv#32]
Hello,

I may be missing something, but pyenv_global seems to have no effect for me when deploying to a Ubuntu Xenial machine.

Relevant playbook snippet:
```
  roles:
    - role: avanov.pyenv
      pyenv_owner: "{{ ubuntu_common_deploy_user_name }}"
      pyenv_path: "/home/{{ ubuntu_common_deploy_user_name }}/pyenv"
      pyenv_global: "3.7.2"
      pyenv_python_versions:
        - "3.7.2"
```

When I log in and run `pyenv versions`, this is the output:

```
deploy@10.10.0.1234:~$ pyenv versions
* system (set by /home/deploy/pyenv/version)
  3.7.2
```
