### ISSUE TITLE
Python is installed, but virtualenv is not

### ISSUE THREAD

**Issue by adborden** [avanov/ansible-galaxy-pyenv#34]
I want to use pyenv to install python, but then individual virtualenvs separately. However, I was surprised when virtualenv was not installed with python.
```yaml
- name: install requested python version with pyenv
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "/home/app/.pyenv"
    pyenv_owner: "app"
    pyenv_global: "2.7.15"
    pyenv_python_versions: ["2.7.15"]
    pyenv_virtualenvs: []

- name: make sure virtualenv is ready
  pip: >-
    executable=/home/app/.pyenv/versions/2.7.15/bin/pip
    name=virtualenv
    state=present
    umask=0022
  become: true
  become_user: "app"
```

And I get this error:
```
    The full traceback is:
    WARNING: The below traceback may *not* be related to the actual failure.
      File "/tmp/ansible_pip_payload_WhiXU_/__main__.py", line 240, in <module>
        from pkg_resources import Requirement

    fatal: [python-app-trusty]: FAILED! => {
        "changed": false,
        "invocation": {
            "module_args": {
                "chdir": null,
                "editable": false,
                "executable": "/home/app/.pyenv/versions/2.7.15/bin/pip",
                "extra_args": null,
                "name": [
                    "virtualenv"
                ],
                "requirements": null,
                "state": "present",
                "umask": "0022",
                "use_mirrors": true,
                "version": null,
                "virtualenv": null,
                "virtualenv_command": "virtualenv",
                "virtualenv_python": null,
                "virtualenv_site_packages": false
            }
        },
        "msg": "No setuptools found in remote host, please install it first."
    }

    PLAY RECAP *********************************************************************
    python-app-trusty          : ok=13   changed=10   unreachable=0    failed=1
```
