### ISSUE TITLE
Installing undefined virtual envs

### ISSUE THREAD

**Issue by jakob1379** [avanov/ansible-galaxy-pyenv#69]
Why is it trying to  install  a virtual env i did not define??

the playbook:
``` yaml
---
- name: Install Pyenv for user gitlab-runner
  hosts: gitlab-22
  vars_files:
    - "{{ become_passwords }}"
  roles:
    - role: pyenv
      become: yes
      pyenv_global: "3.6.5"
      pyenv_path: "/home/jga/.pyenv"
      pyenv_owner: "jga"
      pyenv_update_git_install: no
      pyenv_enable_autocompletion: no
      pyenv_python_versions:
        - "3.8.5"
```

The error
``` yaml
TASK [pyenv : Create virtual environments] *************************************************************************************************************************************************
task path: /home/jga/Documents/it/deploy/roles/external/pyenv/tasks/install.yml:61
failed: [gitlab-22] (item={'venv_name': 'latest', 'py_version': '3.5.0'}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": ". /home/jga/.pyenv/.pyenvrc && pyenv virtualenv 3.5.0 latest",
    "delta": "0:00:00.401261",
    "end": "2022-08-30 07:43:59.637853",
    "item": {
        "py_version": "3.5.0",
        "venv_name": "latest"
    },
    "rc": 1,
    "start": "2022-08-30 07:43:59.236592"
}

STDERR:

pyenv-virtualenv: `3.5.0' is not installed in pyenv.


MSG:

non-zero return code
```
